zeppelin:
  image: cryeo/docker-zeppelin-xgboost
  environment:
    ZEPPELIN_PORT: 8080
    ZEPPELIN_JAVA_OPTS: >-
      -Dspark.driver.memory=1g
      -Dspark.executor.memory=2g
    SPARK_SUBMIT_OPTIONS: >-
      --packages ml.dmlc:xgboost4j:0.7,ml.dmlc:xgboost4j-spark:0.7
    MASTER: local[*]
  ports:
    - 8080:8080
  volumes:
    - ./data:/usr/zeppelin/data
    - ./notebooks:/usr/zeppelin/notebook
